### ISSUE TITLE
Integrate pipestat schema with looper output schema

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#20]
Could the pipestat schema be adapted to integrate with the looper output schema? See #16

> The [looper output schema](https://looper.databio.org/en/latest/pipeline-interface-specification/#output_schema) formally specifies the output produced by this pipeline. It is used by downstream tools to that need to be aware of the products of the pipeline for further visualization or analysis. Like the input schema, it is based on the extended [PEP JSON-schema validation framework](http://pep.databio.org/en/latest/howto_schema/), but adds looper-specific capabilities. 

Currently, the looper schema is used to define the *output files* of the pipeline. Each of these includes a `path` and the types are specified as being one of `link`, `image`, or `file`. 

But pipelines also produce statistics -- primitive types, like `string` or `int`. In fact, that is what the pipestat schema specifies.

It would be more convenient if these two schemas became one. If looper is pipestat-aware, then the looper output schema should just be the pipestat schema. To do this:

- the looper schema would need to be adapted to allow it to specify pipestat types.
- the pipestat schema would have to be adapted to allow it to accommodate the looper types

Then, the two schemas could be combined; the pipeline interface would point to the pipestat schema as the output schema. Looper would use pipestat to manage outputs.

**Comment by nsheff** [comment]
@stolarczyk If you have any comment/insight here it would be helpful now since we're going to dot his soon.

**Comment by nsheff** [comment]
Old example pipestat schema (from [docs](http://127.0.0.1:8000/pipestat_specification/#pipestat-schema)).

```
number_of_things:
  type: integer
  description: "Number of things, min 20, multiple of 10"
  multipleOf: 10
  minimum: 20
name_of_something:
  type: string
  description: "Name of something, min len 2 characters"
  minLength: 2
collection_of_things:
  type: array
  items:
    type: string
  description: "This store collection of strings"
output_object:
  type: object
  properties:
    property1:
      array:
        items:
          type: integer
    property2:
      type: boolean
  required:
    - property1
  description: "Object output with required array of integers and optional boolean"
 ```

 Old example looper output schema (from [docs](https://looper.databio.org/en/latest/pipeline-interface-specification/#output_schema))

 ```
description: objects produced by PEPPRO pipeline.
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        smooth_bw: 
          path: "aligned_{genome}/{sample_name}_smooth.bw"
          type: string
          description: "A smooth bigwig file"
        aligned_bam: 
          path: "aligned_{genome}/{sample_name}_sort.bam"
          type: string
          description: "A sorted, aligned BAM file"
        peaks_bed: 
          path: "peak_calling_{genome}/{sample_name}_peaks.bed"
          type: string
          description: "Peaks in BED format"
  tss_file:
    title: "TSS enrichment file"
    description: "Plots TSS scores for each sample."
    thumbnail_path: "summary/{name}_TSSEnrichment.png"
    path: "summary/{name}_TSSEnrichment.pdf"
    type: image
  counts_table:
    title: "Project peak coverage file"
    description: "Project peak coverages: chr_start_end X sample"
    path: "summary/{name}_peaks_coverage.tsv"
    type: link
 ```

Combining these, into the new "pipestat output schema", I could naively get something like this:


```
description: Pipestat output schema describing outputs of PEPPRO pipeline.
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        smooth_bw: 
          path: "aligned_{genome}/{sample_name}_smooth.bw"
          type: string
          description: "A smooth bigwig file"
        aligned_bam: 
          path: "aligned_{genome}/{sample_name}_sort.bam"
          type: string
          description: "A sorted, aligned BAM file"
        peaks_bed: 
          path: "peak_calling_{genome}/{sample_name}_peaks.bed"
          type: string
          description: "Peaks in BED format"
  tss_file:
    title: "TSS enrichment file"
    description: "Plots TSS scores for each sample."
    thumbnail_path: "summary/{name}_TSSEnrichment.png"
    path: "summary/{name}_TSSEnrichment.pdf"
    type: image
  counts_table:
    title: "Project peak coverage file"
    description: "Project peak coverages: chr_start_end X sample"
    path: "summary/{name}_peaks_coverage.tsv"
    type: link
  number_of_things:
    type: integer
    description: "Number of things, min 20, multiple of 10"
    multipleOf: 10
    minimum: 20
  name_of_something:
    type: string
    description: "Name of something, min len 2 characters"
    minLength: 2
  collection_of_things:
    type: array
    items:
      type: string
    description: "This store collection of strings"
  output_object:
    type: object
    properties:
      property1:
        array:
          items:
            type: integer
      property2:
        type: boolean
    required:
      - property1
    description: "Object output with required array of integers and optional boolean"
```
