### ISSUE TITLE
Docs don't indent bulleted list for attributes of file and image

### ISSUE THREAD

**Issue by vreuter** [pepkit/pipestat#32]
This is in the pipeline specification section of the docs:
```
    file:
    path: path to the reported file
    title: human readable description of the file
    image:
    path: path to the reported image, usually PDF
    thumbnail: path to the reported thumbnail, usually PNG or JPEG
    title: human readable description of the image
```

The lack of nesting is confusing, as `file` and `image` should be the top-level names, with the others nested beneath them.
