### ISSUE TITLE
Set project_level bool in CLI and/or in config file

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#37]
Currently, in branch [sqlmodel](https://github.com/pepkit/pipestat/pull/36), there is not a way to set pipestat to report sample level or project level results using either CLI or in the config file. However, this can be accomplished when calling pipestat in python:
`psm.report(values={"percentage_of_things": "10"}, strict_type=False, project_level=False)`

If you give pipestat a sample_output.yaml file with both project and sample items and attempt to report a value it will give the following error:
'Exception: Cannot determine table suffix with 2 models present and no project-level flag'

Example sample output yaml:
```
pipeline_id: test_pipe
project:
  number_of_things:
    type: integer
    description: "Number of things"
samples:
  percentage_of_things:
    type: number
    description: "Percentage of things"

```

Example database_config.yaml:
```
namespace: test
record_identifier: sample1
schema_path: drc_sample_output_schema.yaml
database:
  dialect: postgresql
  driver: psycopg2
  name: pipestat-test
  user: postgres
  password: pipestat-password
  host: 127.0.0.1
  port: 5432
```
Suggested solutions/additions:
1. Add function that will parse `project_level: true` within the config file such that it is passed to the pipestat object for correctly reporting either sample or pipeline results.
2. Add optional CLI flag to do the above.

For solution 1, add function in pipestat.py here:
https://github.com/pepkit/pipestat/blob/faad7b1780cbb397046ad734f2e492fe6d65aaf2/pipestat/pipestat.py#L185-L206
