### ISSUE TITLE
Support complex objects in database backend by using JSON objects

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#40]
Pipestat should support complex objects (see example below) and store them in as JSON objects in the database. Currently, with the transition to sqlmodel, this functionality is not implemented.

```
pipeline_id: test_pipe
samples:
  collection_of_images:
    description: "This store collection of values"
    type: array
    items:
      type: file
  output_file_in_object:
    type: object
    properties:
      prop1:
        description: "This is an example file"
        type: file
      prop2:
        description: "This is an example image"
        type: image
    description: "Object output"
  output_file:
    type: file
    description: "This a path to the output file"
  output_image:
    type: image
    description: "This a path to the output image"
```
