### ISSUE TITLE
Namespace should be captured as a column in the database

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#41]
Currently capture pipeline ID as tablename (e.g 'test_pipe') but the namespace (e.g. 'namespace: test') should also be captured into the database.

Example yaml:

**Sample output:**
```
pipeline_id: test_pipe
project:
  number_of_things:
    type: integer
    description: "Number of things"
samples:
  percentage_of_things:
    type: number
    description: "Percentage of things"

```

**Sample config.yaml:**
```
namespace: test
record_identifier: sample4
schema_path: drc_sample_output_schema.yaml
database:
  dialect: postgresql
  driver: psycopg2
  name: pipestat-test
  user: postgres
  password: pipestat-password
  host: 127.0.0.1
  port: 5432

```
