### ISSUE TITLE
The pipestat schema should be a JSON Schema.

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#85]
The pipestat schema should be a JSON Schema. This will make it more familiar to people.

**Comment by donaldcampbelljr** [comment]
Some notes on this:

1. Right now, pipestat takes a config_dict or config file and validates it using a json schema validator:
https://github.com/pepkit/pipestat/blob/7de7b5ede177c7c9e052a669a6854e764b34522f/pipestat/pipestat.py#L94-L96

However, it appears that we currently do not perform json schema validation on the output_schema. This make sense since it is not a JSON Schema. Should we perform this validation during schema processing (in `parsed_schema.py`)?

2. I assume we will still use a `.yaml` for the output schema, it will simply need to conform to JSON schema requirements.

3. From some reading, there are some subtle differences between the current `.yaml` schemas and a JSON schema in yaml format. For example:

Current example of an output schema as a `.yaml`:
```
pipeline_name: default_pipeline_name  
samples:  
  collection_of_images:  
    description: "This store collection of values or objects"  
    type: array  
    items:  
      properties:  
          prop1:  
            description: "This is an example file"  
            type: file  
  output_file_in_object:  
    type: object  
    properties:  
      prop1:  
        description: "This is an example file"  
        type: file  
      prop2:  
        description: "This is an example image"  
        type: image  
    description: "Object output"  
  output_file:  
    type: file  
    description: "This a path to the output file"  
  output_image:  
    type: image  
    description: "This a path to the output image"
```
The same schema in proper JSON schema format (as a `.yaml`):
```
$schema: https://json-schema.org/draft/2020-12/schema
$id: https://example.com/output_schema.json
type: object
title: Default Pipeline
description: A pipeline that collects images and outputs a file and an image.
properties:
  pipeline_name:
    type: string
    default: default_pipeline_name
  samples:
    type: object
    properties:
      collection_of_images:
        type: array
        description: A collection of images.
        items:
          type: object
          properties:
            prop1:
              type: file
              description: An example file.
      output_file_in_object:
        type: object
        description: An object containing output files.
        properties:
          prop1:
            type: file
            description: An example file.
          prop2:
            type: image
            description: An example image.
  output_file:
    type: file
    description: The path to the output file.
  output_image:
    type: image
    description: The path to the output image.

```
My understanding regarding $id and $schema:
-if $schema is not declared the latest draft will be used (which should we use?)
-if $id is not declared, the schema can only be used locally (this seems fine).

Next steps:
1. Change schemas to conform to JSON schema
2. Update schema parsing functions (including recursive functions for complex objects) to handle JSON schemas.
3. Add validation to confirm given output_schema is a valid JSON schema.

Do you have any other thoughts on this @nsheff ?
